[build]
  functions = "netlify/functions"
  command = "npm run build" # Specify your build command here
  publish = "public"       # If you have static assets

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200